name: socialio
description: Social app.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  go_router: ^5.1.1
  hooks_riverpod: ^2.1.0
  lottie: ^1.4.3
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  firebase_storage: ^11.0.3
  cloud_kit: ^1.1.0
  cloud_firestore: ^4.0.3
  font_awesome: ^5.10.1
  flutter_facebook_auth: ^5.0.1
  google_sign_in: ^5.4.2
  uuid: ^3.0.6
  image: ^3.2.2
  flutter_hooks: ^0.18.5+1
  collection: ^1.16.0
  intl: ^0.17.0
  video_thumbnail: ^0.5.3
  video_player: ^2.4.7
  share_plus: ^6.2.0
  url_launcher: ^6.1.6
  freezed: ^2.2.1
  font_awesome_flutter: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    # - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  
